import * as THREE from "/vendor/three.module.js";
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const color=(v)=>Number.isInteger(v)?new THREE.Color(((v>>>24)&255)/255,((v>>>16)&255)/255,((v>>>8)&255)/255):Array.isArray(v)?new THREE.Color(...v.slice(0,3).map(x=>x/(v.some(n=>n>1)?255:1))):new THREE.Color(0x63d6a6);
function create(container,hooks={}){
 let renderer,camera,scene,solids,edges,references,supports,bonds,frames=[],bodies=[],continuum=false,groundY=0,frame=0,playing=false,speed=1,magnification=1,last=0,elapsed=0,pointer=null,dead=false,target=new THREE.Vector3(),radius=5,azimuth=.75,polar=1.05;
 const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();ray.params.Line.threshold=.004;
 try{renderer=new THREE.WebGLRenderer({antialias:true});}catch(e){throw new Error(`WebGL could not start: ${e.message}`)}renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x091013);renderer.outputColorSpace=THREE.SRGBColorSpace;container.replaceChildren(renderer.domElement);
 scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(42,1,.0001,1e4);scene.add(new THREE.HemisphereLight(0xdfffee,0x172128,2.1));const sun=new THREE.DirectionalLight(0xffffff,2.2);sun.position.set(4,8,5);scene.add(sun);const grid=new THREE.GridHelper(12,24,0x36514d,0x1b302f);grid.material.transparent=true;grid.material.opacity=.35;scene.add(grid);solids=new THREE.Group();edges=new THREE.Group();references=new THREE.Group();supports=new THREE.Group();bonds=new THREE.Group();scene.add(references,supports,solids,edges,bonds);
 const dispose=g=>{while(g.children.length){const o=g.children.pop();o.traverse(n=>{n.geometry?.dispose();if(Array.isArray(n.material))n.material.forEach(m=>m.dispose());else n.material?.dispose()})}};
 const cameraUpdate=()=>{camera.position.set(target.x+radius*Math.sin(polar)*Math.sin(azimuth),target.y+radius*Math.cos(polar),target.z+radius*Math.sin(polar)*Math.cos(azimuth));camera.lookAt(target)};
 function fit(){const box=new THREE.Box3().setFromObject(solids);if(box.isEmpty())return;box.getCenter(target);const d=box.getSize(new THREE.Vector3()).length();radius=Math.max(d*1.35,.03);grid.scale.setScalar(Math.max(d/12,.005));grid.position.y=continuum?box.min.y:groundY;cameraUpdate()}
 function primitive(b){let g;if(b.shape==="sphere")g=new THREE.SphereGeometry((b.dimensions_m?.[0]||.1)/2,18,12);else if(b.shape==="mesh"&&b.local_triangles_m){g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.Float32BufferAttribute(b.local_triangles_m.flat(2),3));g.computeVertexNormals()}else g=new THREE.BoxGeometry(...(b.dimensions_m||[.1,.1,.1]));const m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:color(b.color_rgba),roughness:.55,metalness:.08,transparent:true}));m.userData={kind:"constituent cell",id:b.id,object_id:b.object_id,element_id:b.element_id,material_id:b.material_id};return m}
 function wire(mesh,data){const w=new THREE.LineSegments(new THREE.EdgesGeometry(mesh.geometry,20),new THREE.LineBasicMaterial({color:0xd8eee7,transparent:true,opacity:.55}));w.userData={kind:"cell structure",id:data.id,material_id:data.material_id};edges.add(w);return w}
 function triangleLines(ts){const a=[];(ts||[]).forEach(t=>{if(Array.isArray(t?.[0]))[[0,1],[1,2],[2,0]].forEach(([i,j])=>a.push(...t[i],...t[j]))});if(!a.length)return;const g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.Float32BufferAttribute(a,3));const l=new THREE.LineSegments(g,new THREE.LineBasicMaterial({color:0x8fa19f,transparent:true,opacity:.65}));l.userData={kind:"support boundary"};supports.add(l)}
 function buildNetwork(d){continuum=false;const ys=(d.supports||[]).flat(2).filter((_,i)=>i%3===1);groundY=ys.length?Math.min(...ys):0;bodies=d.bodies||[];bodies.forEach(b=>{b.mesh=primitive(b);solids.add(b.mesh);b.edge=wire(b.mesh,b)});triangleLines(d.supports);frames=d.frames||[]}
 function internalLines(ps,es,offset,material){const pairs=[];(es||[]).forEach(e=>{for(let i=0;i<e.length;i++)for(let j=i+1;j<e.length;j++)if(ps[e[i]]&&ps[e[j]])pairs.push([e[i],e[j]])});if(!pairs.length)return null;const g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.Float32BufferAttribute(pairs.flatMap(([i,j])=>[...ps[i],...ps[j]]),3));const line=new THREE.LineSegments(g,new THREE.LineBasicMaterial({color:0xd8eee7,transparent:true,opacity:.22}));line.position.copy(offset);line.userData={kind:"deformed element structure",material_id:material};line.onBeforeRender=()=>{const b=bodies.find(x=>x.material_id===material),s=b?.frames[Math.min(frame,b.frames.length-1)],ds=s?.displacements_m||[],a=line.geometry.attributes.position;let n=0;pairs.forEach(([i,j])=>[i,j].forEach(k=>{const p=ps[k],d=ds[k]||[0,0,0];a.setXYZ(n++,p[0]+d[0]*magnification,p[1]+d[1]*magnification,p[2]+d[2]*magnification)}));a.needsUpdate=true};edges.add(line);return{line,pairs}}
 function buildContinuum(d){continuum=true;const sets=Array.isArray(d.cases)?d.cases:Array.isArray(d.materials)?d.materials:[d],palette=[0x62d6a5,0xe7bf74,0x89bff0];let count=0;sets.forEach((s,i)=>{const ps=s.reference_positions_m||d.reference_positions_m||[],tris=s.boundary_triangles||d.boundary_triangles||[],offset=new THREE.Vector3(i*.06,0,0),g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.Float32BufferAttribute(ps.flat(),3));if(tris.length)g.setIndex(tris.flat());g.computeVertexNormals();const material=s.material_id||`material-${i+1}`,m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:palette[i%3],side:THREE.DoubleSide,roughness:.7,transparent:true}));m.position.copy(offset);m.userData={kind:"material column",material_id:material,status:s.status};solids.add(m);const ref=new THREE.LineSegments(new THREE.WireframeGeometry(g.clone()),new THREE.LineBasicMaterial({color:0xa8bbb7,transparent:true,opacity:.32}));ref.position.copy(offset);ref.userData={kind:"reference shape",material_id:material};references.add(ref);const structure=internalLines(ps,s.elements||d.elements,offset,material);const accepted=(s.frames||d.frames||[]).filter(f=>f?.accepted!==false);count=Math.max(count,accepted.length);bodies.push({mesh:m,structure,positions:ps,frames:accepted,status:s.status,material_id:material})});frames=Array.from({length:count},(_,i)=>{const samples=bodies.map(b=>b.frames[Math.min(i,b.frames.length-1)]).filter(Boolean),r=samples[0]||{};return{phase:r.phase,load_fraction:r.load_fraction,load_frame:i+1,material_states:bodies.map((b,j)=>({material_id:b.material_id,status:b.status,phase:samples[j]?.phase,load_fraction:samples[j]?.load_fraction,maximum_equivalent_plastic_strain:samples[j]?.maximum_equivalent_plastic_strain,maximum_displacement_m:samples[j]?.maximum_displacement_m}))}})}
 function bondLines(list){dispose(bonds);if(!list?.length)return;const p=[],c=[];list.forEach(b=>{p.push(...b.a_m,...b.b_m);const x=new THREE.Color(b.live===false?0xf18b88:b.damage>0?0xf6c572:0x8de6be);c.push(x.r,x.g,x.b,x.r,x.g,x.b)});const g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.Float32BufferAttribute(p,3));g.setAttribute("color",new THREE.Float32BufferAttribute(c,3));const l=new THREE.LineSegments(g,new THREE.LineBasicMaterial({vertexColors:true,transparent:true,opacity:.85}));l.userData={kind:"bond network",bond_count:list.length,broken_count:list.filter(b=>b.live===false).length,damaged_count:list.filter(b=>b.damage>0).length};bonds.add(l)}
 function setPlaying(v){playing=!!v;elapsed=0;hooks.onPlayState?.(playing);return playing}
 function update(i){frame=clamp(Math.round(i),0,Math.max(0,frames.length-1));const f=frames[frame]||{};if(continuum)bodies.forEach(b=>{const s=b.frames[Math.min(frame,b.frames.length-1)];if(!s)return;const ds=s.displacements_m||[],a=b.mesh.geometry.attributes.position;for(let n=0;n<b.positions.length;n++){const p=b.positions[n],q=ds[n]||[0,0,0];a.setXYZ(n,p[0]+q[0]*magnification,p[1]+q[1]*magnification,p[2]+q[2]*magnification)}a.needsUpdate=true;b.mesh.geometry.computeVertexNormals();b.mesh.userData={kind:"material column",material_id:b.material_id,status:b.status,phase:s.phase,load_fraction:s.load_fraction,max_eqp:s.max_eqp??s.maxeqp}});else{const poses=new Map((f.poses||[]).map(p=>[p.id,p]));bodies.forEach(b=>{const m=b.mesh,p=poses.get(b.id);m.visible=!!p;b.edge.visible=!!p;if(!p)return;m.position.fromArray(p.position_m||[0,0,0]);const q=p.orientation_wxyz||[1,0,0,0];m.quaternion.set(q[1],q[2],q[3],q[0]);b.edge.position.copy(m.position);b.edge.quaternion.copy(m.quaternion);m.userData.component_id=p.component_id});bondLines(f.bonds||[])}hooks.onFrame?.({index:frame,count:frames.length,frame:f,continuum})}
 function load(d){setPlaying(false);[solids,edges,references,supports,bonds].forEach(dispose);bodies=[];frames=[];frame=0;if(d?.schema==="banjo.playback.v1"){magnification=1;buildNetwork(d)}else if(d?.schema==="banjo.continuum-patch-trial.v1"||d?.cases)buildContinuum(d);else throw new Error("This result has no supported playback geometry.");references.visible=false;edges.visible=true;bonds.visible=true;update(0);fit();return{continuum,magnification}}
 const delay=()=>continuum?150:(Number.isFinite(frames[frame]?.time_s)&&frames[frame+1]?.time_s>frames[frame].time_s?(frames[frame+1].time_s-frames[frame].time_s)*1000:120);
 function loop(now){if(dead)return;const w=Math.max(1,container.clientWidth),h=Math.max(1,container.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();if(playing&&frames.length>1){elapsed+=(now-last)*speed;let d=delay();while(playing&&elapsed>=d){elapsed-=d;if(frame>=frames.length-1){setPlaying(false);break}update(frame+1);d=delay()}}if(continuum)bodies.forEach(b=>{const s=b.frames[Math.min(frame,b.frames.length-1)];if(s)b.mesh.userData={kind:"material column",material_id:b.material_id,status:b.status,phase:s.phase,load_fraction:s.load_fraction,maximum_equivalent_plastic_strain:s.maximum_equivalent_plastic_strain,maximum_displacement_m:s.maximum_displacement_m}});last=now;cameraUpdate();renderer.render(scene,camera);requestAnimationFrame(loop)}
 const canvas=renderer.domElement;canvas.addEventListener("pointerdown",e=>{pointer={x:e.clientX,y:e.clientY,azimuth,polar,moved:false};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener("pointermove",e=>{if(!pointer)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(Math.abs(dx)+Math.abs(dy)>3)pointer.moved=true;azimuth=pointer.azimuth-dx*.007;polar=clamp(pointer.polar+dy*.007,.08,Math.PI-.08)});canvas.addEventListener("pointerup",e=>{if(pointer&&!pointer.moved){const r=canvas.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);hooks.onInspect?.(ray.intersectObjects([solids,edges,bonds,references,supports],true)[0]?.object?.userData||null)}pointer=null});canvas.addEventListener("wheel",e=>{e.preventDefault();radius=clamp(radius*Math.exp(e.deltaY*.001),.002,1e4)},{passive:false});requestAnimationFrame(loop);
 return{load,play:v=>setPlaying(v??!playing),reset(){setPlaying(false);update(0);fit()},step(n){setPlaying(false);update(frame+n)},setFrame(i){setPlaying(false);update(i)},setSpeed(v){speed=clamp(Number(v)||1,.1,4)},setMagnification(v){magnification=clamp(Number(v)||1,1,100);update(frame)},showReference(v){references.visible=!!v},showBonds(v){bonds.visible=!!v},showComponents(v){edges.visible=!!v},setXray(v){solids.traverse(o=>{if(o.material){o.material.opacity=v?.32:1;o.material.transparent=!!v}})},get frameCount(){return frames.length},get frame(){return frame},dispose(){dead=true;renderer.dispose();[solids,edges,references,supports,bonds].forEach(dispose)}}
}
window.BanjoScene={create,THREE_VERSION:THREE.REVISION};window.dispatchEvent(new Event("banjo-scene-ready"));
