"""The asset compiler's fixtures, built by code rather than downloaded.

Five cases, each chosen because it fails in a different way if the compiler is
wrong, and each with an analytic volume so the occupancy has something exact to
be measured against:

- a solid block, which must convert exactly;
- an open-topped cup, whose cavity must stay empty;
- a plate thinner than one cell, which must be REFUSED rather than thickened;
- two blocks either side of a 10 mm slot, which the bond horizon would weld shut;
- one stair tread, instanced twelve times, which must be converted once.

Every shape is built out of axis-aligned boxes whose interiors do not meet, so
the mesh is a set of closed shells: each shell is watertight on its own, the
divergence-theorem volume is the exact sum of the boxes, and the scan's winding
number handles the coincident faces where two boxes touch.

    python tools/asset_fixtures.py --out some/directory
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any

# Everything here is authored in millimetres and DECLARES that in its assembly
# document, because the compiler refuses to guess a unit.
UNIT = "mm"
CELL_MM = 10.0

# What the fixtures are, in millimetres. The block is 20 by 12 by 8 cells at a
# 10 mm cell, so a correct conversion is exact and any error is the compiler's
# rather than the fixture's.
BLOCK_MM = (200.0, 120.0, 80.0)

# A cup: a base slab and four walls, each 20 mm thick, around an 80 mm cavity
# that is open at the top. Two cells of wall is deliberate -- one cell of wall
# would itself be a feature at the resolution limit and would confuse the case
# this fixture is for, which is the cavity.
CUP_OUTER_MM = (120.0, 100.0, 120.0)
CUP_WALL_MM = 20.0

# A plate 3 mm through, sitting from y = 3 to y = 6 mm so that the cell centre
# plane at y = 5 mm lies INSIDE it. Centre sampling would therefore report a
# full 10 mm slab: the failure this fixture exists to catch is silent
# thickening, not a silent disappearance.
PLATE_MM = (200.0, 3.0, 200.0)
PLATE_BOTTOM_MM = 3.0

# Two 60 mm blocks with a 10 mm slot between them, fused into one body. At a
# 10 mm cell and the generator's horizon of 2 cells, the columns either side of
# the slot are exactly 2 cells apart, which is inside the horizon.
SLOT_BLOCK_MM = 60.0
SLOT_GAP_MM = 10.0

# One tread, instanced twelve times up and along. The rise and the going are
# whole numbers of cells, so no instance needs its translation snapped.
TREAD_MM = (300.0, 40.0, 200.0)
TREAD_RISE_MM = 160.0
TREAD_GOING_MM = 200.0
TREAD_COUNT = 12

RIGHTS = {"source": "generated by tools/asset_fixtures.py",
          "licence": "as this repository", "verified_by": "generation"}


def box(lo: tuple[float, float, float], hi: tuple[float, float, float]) -> dict[str, Any]:
    """A closed box with outward-facing triangles."""
    x0, y0, z0 = lo
    x1, y1, z1 = hi
    vertices = [(x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0),
                (x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)]
    triangles = [(0, 3, 2), (0, 2, 1),   # z = z0, outward is -z
                 (4, 5, 6), (4, 6, 7),   # z = z1
                 (0, 1, 5), (0, 5, 4),   # y = y0
                 (3, 7, 6), (3, 6, 2),   # y = y1
                 (0, 4, 7), (0, 7, 3),   # x = x0
                 (1, 2, 6), (1, 6, 5)]   # x = x1
    return {"vertices": vertices, "triangles": triangles,
            "volume": (x1 - x0) * (y1 - y0) * (z1 - z0)}


def merged(*boxes: dict[str, Any]) -> dict[str, Any]:
    """Several shells in one mesh, with the volumes added up."""
    vertices: list[tuple[float, float, float]] = []
    triangles: list[tuple[int, int, int]] = []
    volume = 0.0
    for shell in boxes:
        offset = len(vertices)
        vertices.extend(shell["vertices"])
        triangles.extend((a + offset, b + offset, c + offset) for a, b, c in shell["triangles"])
        volume += shell["volume"]
    return {"vertices": vertices, "triangles": triangles, "volume": volume}


def solid_block() -> dict[str, Any]:
    return box((0.0, 0.0, 0.0), BLOCK_MM)


def open_cup() -> dict[str, Any]:
    """A base and four walls. Nothing closes the top, so the cavity is not solid."""
    width, height, depth = CUP_OUTER_MM
    wall = CUP_WALL_MM
    return merged(box((0.0, 0.0, 0.0), (width, wall, depth)),
                  box((0.0, wall, 0.0), (wall, height, depth)),
                  box((width - wall, wall, 0.0), (width, height, depth)),
                  box((wall, wall, 0.0), (width - wall, height, wall)),
                  box((wall, wall, depth - wall), (width - wall, height, depth)))


def thin_plate() -> dict[str, Any]:
    width, thickness, depth = PLATE_MM
    return box((0.0, PLATE_BOTTOM_MM, 0.0), (width, PLATE_BOTTOM_MM + thickness, depth))


def slot_block() -> dict[str, Any]:
    side = SLOT_BLOCK_MM
    return box((0.0, 0.0, 0.0), (side, side, side))


def stair_tread() -> dict[str, Any]:
    return box((0.0, 0.0, 0.0), TREAD_MM)


MESHES = {"block": solid_block, "cup": open_cup, "plate": thin_plate,
          "slot_block": slot_block, "tread": stair_tread}

ANALYTIC_VOLUME_MM3 = {name: builder()["volume"] for name, builder in MESHES.items()}


def rotated(mesh: dict[str, Any], degrees: tuple[float, float, float]) -> dict[str, Any]:
    """The same mesh turned, in the engine's order: x, then y, then z.

    That is the order src/fastlattice/TileImpactScene.cpp:53 applies. A quarter
    turn uses exact integers rather than math.cos, so a mesh turned by 90
    degrees lands exactly on the grid it came from and a comparison of cells is
    a comparison rather than a tolerance.
    """
    import math

    def turn(point, axis, angle):
        if angle % 90 == 0:
            cos, sin = ((1, 0), (0, 1), (-1, 0), (0, -1))[int(angle // 90) % 4]
        else:
            radians = angle * math.pi / 180.0
            cos, sin = math.cos(radians), math.sin(radians)
        u, v = ((1, 2), (2, 0), (0, 1))[axis]
        out = list(point)
        out[u] = point[u] * cos - point[v] * sin
        out[v] = point[u] * sin + point[v] * cos
        return tuple(out)

    vertices = []
    for vertex in mesh["vertices"]:
        for axis in range(3):
            vertex = turn(vertex, axis, degrees[axis])
        vertices.append(vertex)
    return {"vertices": vertices, "triangles": list(mesh["triangles"]), "volume": mesh["volume"]}


def write_obj(path: Path, mesh: dict[str, Any]) -> Path:
    """The mesh as a Wavefront OBJ, which the compiler reads with no dependency."""
    lines = [f"# {path.stem}, generated by tools/asset_fixtures.py; units are {UNIT}"]
    lines.extend(f"v {x:.6f} {y:.6f} {z:.6f}" for x, y, z in mesh["vertices"])
    lines.extend(f"f {a + 1} {b + 1} {c + 1}" for a, b, c in mesh["triangles"])
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def _document(parts: dict[str, Any], instances: list[dict[str, Any]],
              connections: list[dict[str, Any]] | None = None,
              cell_mm: float = CELL_MM) -> dict[str, Any]:
    document = {"schema": "banjo.asset-assembly.v1", "cell_size_m": cell_mm / 1000.0,
                "neighbor_horizon_cells": 2, "rights": dict(RIGHTS),
                "parts": parts, "instances": instances}
    if connections:
        document["connections"] = connections
    return document


def assemblies(cell_mm: float = CELL_MM) -> dict[str, dict[str, Any]]:
    """One assembly document per fixture, each naming its mesh file."""
    stair = [{"id": f"tread-{step + 1}", "part": "tread",
              "translation_mm": [0.0, TREAD_RISE_MM * step, TREAD_GOING_MM * step]}
             for step in range(TREAD_COUNT)]
    return {
        "block": _document({"block": {"mesh": "block.obj", "unit": UNIT, "material": "oak"}},
                           [{"id": "block", "part": "block"}], cell_mm=cell_mm),
        "cup": _document({"cup": {"mesh": "cup.obj", "unit": UNIT, "material": "oak"}},
                         [{"id": "cup", "part": "cup"}], cell_mm=cell_mm),
        "plate": _document({"plate": {"mesh": "plate.obj", "unit": UNIT, "material": "glass"}},
                           [{"id": "plate", "part": "plate"}], cell_mm=cell_mm),
        # One part, two instances, declared fused: that is what hands both to a
        # single generateVoxelLattice call, which is where the gap is lost.
        "slot": _document({"slot_block": {"mesh": "slot_block.obj", "unit": UNIT, "material": "iron"}},
                          [{"id": "slot-left", "part": "slot_block", "translation_mm": [0.0, 0.0, 0.0]},
                           {"id": "slot-right", "part": "slot_block",
                            "translation_mm": [SLOT_BLOCK_MM + SLOT_GAP_MM, 0.0, 0.0]}],
                          [{"kind": "fixed", "a": "slot-left", "b": "slot-right"}], cell_mm=cell_mm),
        "stair": _document({"tread": {"mesh": "tread.obj", "unit": UNIT, "material": "oak"}},
                           stair, cell_mm=cell_mm),
    }


def build(directory: Path, cell_mm: float = CELL_MM) -> dict[str, Path]:
    """Write every mesh and every assembly document; return where they went."""
    directory.mkdir(parents=True, exist_ok=True)
    written = {}
    for name, builder in MESHES.items():
        written[name] = write_obj(directory / f"{name}.obj", builder())
    for name, document in assemblies(cell_mm).items():
        path = directory / f"{name}.assembly.json"
        path.write_text(json.dumps(document, indent=2), encoding="utf-8")
        written[f"{name}.assembly"] = path
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, required=True, help="where to write the fixtures")
    parser.add_argument("--cell-mm", type=float, default=CELL_MM)
    args = parser.parse_args(argv)
    for name, path in build(args.out, args.cell_mm).items():
        print(f"{name}: {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
