# Read-only hooks in the pinned dependency, generated only in this build tree.
# Consumers share the same header/class layout. Reference expressions are unchanged.
# An explicit experimental callback supplies centered pose velocities; absent
# that callback, the pinned native integration expressions remain identical.
function(banjo_jolt_force_observation target source_dir)
    set(overlay "${CMAKE_CURRENT_BINARY_DIR}/jolt-force-observation-overlay")
    file(MAKE_DIRECTORY "${overlay}/Jolt/Physics")
    file(READ "${source_dir}/Jolt/Physics/PhysicsSystem.h" header)
    file(READ "${source_dir}/Jolt/Physics/PhysicsSystem.cpp" implementation)
    set(header_marker "\tvoid\t\t\t\t\t\tSetPhysicsSettings(")
    string(FIND "${header}" "${header_marker}" header_position)
    set(force_marker "\t\t\t\tmp->ApplyForceTorqueAndDragInternal(rotation, mGravity, delta_time);")
    string(FIND "${implementation}" "${force_marker}" force_position)
    set(gyro_marker "\t\t\t\tif (body.GetApplyGyroscopicForce())")
    string(FIND "${implementation}" "${gyro_marker}" gyro_position)
    if(header_position LESS 0 OR force_position LESS 0 OR gyro_position LESS 0)
        message(FATAL_ERROR "Pinned Jolt force phase changed; review observation hook placement")
    endif()
    set(callback_api "\t// Banjo read-only observation; configure only between Updates.\n\tusing BanjoForceObserver = void (*)(void *, const Body &, Vec3Arg, Vec3Arg, Vec3Arg, Vec3Arg);\n\tvoid SetBanjoForceObserver(BanjoForceObserver callback, void *context) { mBanjoForceObserver = callback; mBanjoForceContext = context; }\n")
    string(REPLACE "${header_marker}" "${callback_api}${header_marker}" header "${header}")
    string(REPLACE "\tPhysicsSettings\t\t\t\tmPhysicsSettings;" "\tBanjoForceObserver mBanjoForceObserver = nullptr;\n\tvoid *mBanjoForceContext = nullptr;\n\tPhysicsSettings\t\t\t\tmPhysicsSettings;" header "${header}")
    string(FIND "${header}" "mBanjoForceContext = nullptr" member_position)
    if(member_position LESS 0)
        message(FATAL_ERROR "Pinned Jolt PhysicsSystem member layout changed")
    endif()
    string(REPLACE "${gyro_marker}" "\t\t\t\tVec3 banjo_velocity_before, banjo_spin_before;\n\t\t\t\tif (mBanjoForceObserver) { banjo_velocity_before = body.GetLinearVelocity(); banjo_spin_before = body.GetAngularVelocity(); }\n${gyro_marker}" implementation "${implementation}")
    set(observation "\t\t\t\tVec3 banjo_spin_gyro;\n\t\t\t\tif (mBanjoForceObserver) banjo_spin_gyro = body.GetAngularVelocity();\n${force_marker}\n\t\t\t\tif (mBanjoForceObserver) mBanjoForceObserver(mBanjoForceContext, body, banjo_velocity_before, banjo_spin_before, banjo_spin_gyro, (mp->GetGravityFactor() * mGravity) * delta_time);")
    string(REPLACE "${force_marker}" "${observation}" implementation "${implementation}")
    set(limit_marker "\t\t\t\tmp->ClampLinearVelocity();\n\t\t\t\tmp->ClampAngularVelocity();")
    string(FIND "${implementation}" "${limit_marker}" limit_position)
    if(limit_position LESS 0)
        message(FATAL_ERROR "Pinned Jolt integration phase changed; review limit observation hook")
    endif()
    set(limit_api "\tusing BanjoLimitObserver = void (*)(void *, const Body &, Vec3Arg, Vec3Arg);\n\tvoid SetBanjoLimitObserver(BanjoLimitObserver callback, void *context) { mBanjoLimitObserver = callback; mBanjoLimitContext = context; }\n")
    string(REPLACE "${header_marker}" "${limit_api}${header_marker}" header "${header}")
    string(REPLACE "\tBanjoForceObserver mBanjoForceObserver" "\tBanjoLimitObserver mBanjoLimitObserver = nullptr;\n\tvoid *mBanjoLimitContext = nullptr;\n\tBanjoForceObserver mBanjoForceObserver" header "${header}")
    string(REPLACE "${limit_marker}" "\t\t\t\tVec3 banjo_solver_velocity, banjo_solver_spin;\n\t\t\t\tif (mBanjoLimitObserver) { banjo_solver_velocity = body.GetLinearVelocity(); banjo_solver_spin = body.GetAngularVelocity(); }\n${limit_marker}\n\t\t\t\tif (mBanjoLimitObserver) mBanjoLimitObserver(mBanjoLimitContext, body, banjo_solver_velocity, banjo_solver_spin);" implementation "${implementation}")
    set(centered_api "\tusing BanjoCenteredMotion = Vec3 (*)(void *, const Body &, bool);\n\tvoid SetBanjoCenteredMotion(BanjoCenteredMotion callback, void *context) { mBanjoCenteredMotion = callback; mBanjoCenteredContext = context; }\n")
    string(REPLACE "${header_marker}" "${centered_api}${header_marker}" header "${header}")
    string(REPLACE "\tBanjoForceObserver mBanjoForceObserver" "\tBanjoCenteredMotion mBanjoCenteredMotion = nullptr;\n\tvoid *mBanjoCenteredContext = nullptr;\n\tBanjoForceObserver mBanjoForceObserver" header "${header}")
    foreach(expression "body.AddRotationStep(body.GetAngularVelocity() * delta_time);" "Vec3 delta_pos = body.GetLinearVelocity() * delta_time;")
        string(FIND "${implementation}" "${expression}" motion_position)
        if(motion_position LESS 0)
            message(FATAL_ERROR "Pinned Jolt pose integration changed")
        endif()
    endforeach()
    # A refined centered step must not stop rotating while spin remains nonzero.
    # Give this path its own inline rotation method; reference integration and
    # position-constraint corrections retain their pinned expressions.
    file(READ "${source_dir}/Jolt/Physics/Body/Body.h" body_header)
    file(READ "${source_dir}/Jolt/Physics/Body/Body.inl" body_inline)
    set(body_marker "inline void\t\t\t\tAddRotationStep(Vec3Arg inAngularVelocityTimesDeltaTime);")
    string(FIND "${body_header}" "${body_marker}" body_position)
    set(inline_marker "void Body::AddRotationStep(Vec3Arg inAngularVelocityTimesDeltaTime)")
    string(FIND "${body_inline}" "${inline_marker}" inline_position)
    if(body_position LESS 0 OR inline_position LESS 0)
        message(FATAL_ERROR "Pinned Jolt body rotation API changed")
    endif()
    string(REPLACE "${body_marker}" "${body_marker}\n\tinline void AddCenteredRotationStep(Vec3Arg inAngularVelocityTimesDeltaTime);" body_header "${body_header}")
    set(centered_rotation "void Body::AddCenteredRotationStep(Vec3Arg delta)\n{\n\tJPH_ASSERT(IsRigidBody());\n\tJPH_ASSERT(BodyAccess::sCheckRights(BodyAccess::sPositionAccess(), BodyAccess::EAccess::ReadWrite));\n\tconst float len = delta.Length();\n\tif (len > 0.0f)\n\t{\n\t\tmRotation = (Quat::sRotation(delta / len, len) * mRotation).Normalized();\n\t\tJPH_ASSERT(!mRotation.IsNaN());\n\t}\n}\n\n")
    string(REPLACE "${inline_marker}" "${centered_rotation}${inline_marker}" body_inline "${body_inline}")
    file(MAKE_DIRECTORY "${overlay}/Jolt/Physics/Body")
    file(CONFIGURE OUTPUT "${overlay}/Jolt/Physics/Body/Body.h" CONTENT "${body_header}" @ONLY)
    file(CONFIGURE OUTPUT "${overlay}/Jolt/Physics/Body/Body.inl" CONTENT "${body_inline}" @ONLY)
    string(REPLACE "body.AddRotationStep(body.GetAngularVelocity() * delta_time);" "if (mBanjoCenteredMotion) body.AddCenteredRotationStep(mBanjoCenteredMotion(mBanjoCenteredContext, body, true) * delta_time);\n\t\t\telse body.AddRotationStep(body.GetAngularVelocity() * delta_time);" implementation "${implementation}")
    string(REPLACE "Vec3 delta_pos = body.GetLinearVelocity() * delta_time;" "Vec3 delta_pos = (mBanjoCenteredMotion?mBanjoCenteredMotion(mBanjoCenteredContext, body, false):body.GetLinearVelocity()) * delta_time;" implementation "${implementation}")
    file(CONFIGURE OUTPUT "${overlay}/Jolt/Physics/PhysicsSystem.h" CONTENT "${header}" @ONLY)
    file(CONFIGURE OUTPUT "${overlay}/Jolt/Physics/PhysicsSystem.cpp" CONTENT "${implementation}" @ONLY)
    # Opt-in contact bias for the same midpoint trajectory used above.
    # ContactSettings is shared by every consumer, including cached manifolds.
    file(READ "${source_dir}/Jolt/Physics/Collision/ContactListener.h" contact_header)
    set(contact_marker "\tfloat\t\t\t\t\tmCombinedFriction;")
    string(FIND "${contact_header}" "${contact_marker}" contact_header_position)
    if(contact_header_position LESS 0)
        message(FATAL_ERROR "Pinned Jolt contact settings changed")
    endif()
    set(contact_fields "\tbool mBanjoMidpointContact = false;\n\tVec3 mBanjoInitialLinear1 = Vec3::sZero(), mBanjoInitialLinear2 = Vec3::sZero();\n\tVec3 mBanjoInitialAngular1 = Vec3::sZero(), mBanjoInitialAngular2 = Vec3::sZero();\n")
    string(REPLACE "${contact_marker}" "${contact_fields}${contact_marker}" contact_header "${contact_header}")
    file(MAKE_DIRECTORY "${overlay}/Jolt/Physics/Collision" "${overlay}/Jolt/Physics/Constraints")
    file(CONFIGURE OUTPUT "${overlay}/Jolt/Physics/Collision/ContactListener.h" CONTENT "${contact_header}" @ONLY)
    file(READ "${source_dir}/Jolt/Physics/Constraints/ContactConstraintManager.cpp" contact_implementation)
    set(contact_solve_marker "\tmNonPenetrationConstraint.CalculateConstraintProperties(inInvM1, inInvI1, r1, inInvM2, inInvI2, r2, inWorldSpaceNormal, normal_velocity_bias);")
    string(FIND "${contact_implementation}" "${contact_solve_marker}" contact_solve_position)
    if(contact_solve_position LESS 0)
        message(FATAL_ERROR "Pinned Jolt contact solve changed")
    endif()
    # For gap g >= 0, g1 = g + h*(vn0+vn1)/2 >= 0.
    # Therefore vn1 + vn0 + 2*g/h >= 0. No velocity/pose reassignment.
    # Initial overlap is not repaired by an energy-injecting position bias.
    set(midpoint_bias "\tif (inSettings.mBanjoMidpointContact)\n\t{\n\t\tconst Vec3 initial_relative = inSettings.mBanjoInitialLinear2 + inSettings.mBanjoInitialAngular2.Cross(r2) - inSettings.mBanjoInitialLinear1 - inSettings.mBanjoInitialAngular1.Cross(r1);\n\t\tnormal_velocity_bias = initial_relative.Dot(inWorldSpaceNormal) + 2.0f * speculative_contact_velocity_bias;\n\t}\n\n")
    string(REPLACE "${contact_solve_marker}" "${midpoint_bias}${contact_solve_marker}" contact_implementation "${contact_implementation}")
    set(friction_marker "\t\t// Implement friction as 2 ContactConstraintParts")
    set(twist_marker "\t\t\tmAngularFrictionConstraint.CalculateConstraintProperties(inInvI1, inInvI2, inWorldSpaceNormal, inSettings.mRelativeAngularSurfaceVelocity.Dot(inWorldSpaceNormal));")
    string(FIND "${contact_implementation}" "${friction_marker}" friction_position)
    string(FIND "${contact_implementation}" "${twist_marker}" twist_position)
    if(friction_position LESS 0 OR twist_position LESS 0)
        message(FATAL_ERROR "Pinned Jolt friction solve changed")
    endif()
    # Native row solves relative final velocity = -bias. The midpoint law
    # needs (v0+v1)/2 = -surface velocity, under the same Coulomb impulse cap.
    set(midpoint_friction "\t\tif (inSettings.mBanjoMidpointContact)\n\t\t{\n\t\t\tconst Vec3 initial_relative = inSettings.mBanjoInitialLinear2 + inSettings.mBanjoInitialAngular2.Cross(r2) - inSettings.mBanjoInitialLinear1 - inSettings.mBanjoInitialAngular1.Cross(r1);\n\t\t\tsurface_velocity1 = initial_relative.Dot(inWorldSpaceTangent1) + 2.0f * surface_velocity1;\n\t\t\tsurface_velocity2 = initial_relative.Dot(inWorldSpaceTangent2) + 2.0f * surface_velocity2;\n\t\t}\n\n")
    string(REPLACE "${friction_marker}" "${midpoint_friction}${friction_marker}" contact_implementation "${contact_implementation}")
    set(midpoint_twist "\t\t{\n\t\t\tfloat twist_bias = inSettings.mRelativeAngularSurfaceVelocity.Dot(inWorldSpaceNormal);\n\t\t\tif (inSettings.mBanjoMidpointContact) twist_bias = (inSettings.mBanjoInitialAngular2 - inSettings.mBanjoInitialAngular1).Dot(inWorldSpaceNormal) + 2.0f * twist_bias;\n\t\t\tmAngularFrictionConstraint.CalculateConstraintProperties(inInvI1, inInvI2, inWorldSpaceNormal, twist_bias);\n\t\t}")
    string(REPLACE "${twist_marker}" "${midpoint_twist}" contact_implementation "${contact_implementation}")
    file(CONFIGURE OUTPUT "${overlay}/Jolt/Physics/Constraints/ContactConstraintManager.cpp" CONTENT "${contact_implementation}" @ONLY)
    get_target_property(sources ${target} SOURCES)
    foreach(relative "Jolt/Physics/PhysicsSystem.cpp" "Jolt/Physics/Constraints/ContactConstraintManager.cpp")
        get_filename_component(original "${source_dir}/${relative}" REALPATH)
        set(source_position -1)
        set(source_index 0)
        foreach(source IN LISTS sources)
            get_filename_component(candidate "${source}" REALPATH)
            if(candidate STREQUAL original)
                if(NOT source_position LESS 0)
                    message(FATAL_ERROR "Duplicate pinned native source: ${relative}")
                endif()
                set(source_position ${source_index})
            endif()
            math(EXPR source_index "${source_index}+1")
        endforeach()
        if(source_position LESS 0)
            message(FATAL_ERROR "Pinned native source registration changed: ${relative}")
        endif()
        list(REMOVE_AT sources ${source_position})
        list(APPEND sources "${overlay}/${relative}")
    endforeach()
    set_property(TARGET ${target} PROPERTY SOURCES "${sources}")
    target_include_directories(${target} BEFORE PUBLIC "${overlay}")
endfunction()
