# Read-only hooks in the pinned dependency, generated only in this build tree.
# Consumers share the same header/class layout. No force expression is replaced.
function(banjo_jolt_force_observation target source_dir)
    set(overlay "${CMAKE_CURRENT_BINARY_DIR}/jolt-force-observation-overlay")
    file(MAKE_DIRECTORY "${overlay}/Jolt/Physics")
    file(READ "${source_dir}/Jolt/Physics/PhysicsSystem.h" header)
    file(READ "${source_dir}/Jolt/Physics/PhysicsSystem.cpp" implementation)
    set(header_marker "\tvoid\t\t\t\t\t\tSetPhysicsSettings(")
    string(FIND "${header}" "${header_marker}" header_position)
    set(force_marker "\t\t\t\tmp->ApplyForceTorqueAndDragInternal(rotation, mGravity, delta_time);")
    string(FIND "${implementation}" "${force_marker}" force_position)
    set(gyro_marker "\t\t\t\tif (body.GetApplyGyroscopicForce())")
    string(FIND "${implementation}" "${gyro_marker}" gyro_position)
    if(header_position LESS 0 OR force_position LESS 0 OR gyro_position LESS 0)
        message(FATAL_ERROR "Pinned Jolt force phase changed; review observation hook placement")
    endif()
    set(callback_api "\t// Banjo read-only observation; configure only between Updates.\n\tusing BanjoForceObserver = void (*)(void *, const Body &, Vec3Arg, Vec3Arg, Vec3Arg, Vec3Arg);\n\tvoid SetBanjoForceObserver(BanjoForceObserver callback, void *context) { mBanjoForceObserver = callback; mBanjoForceContext = context; }\n")
    string(REPLACE "${header_marker}" "${callback_api}${header_marker}" header "${header}")
    string(REPLACE "\tPhysicsSettings\t\t\t\tmPhysicsSettings;" "\tBanjoForceObserver mBanjoForceObserver = nullptr;\n\tvoid *mBanjoForceContext = nullptr;\n\tPhysicsSettings\t\t\t\tmPhysicsSettings;" header "${header}")
    string(FIND "${header}" "mBanjoForceContext = nullptr" member_position)
    if(member_position LESS 0)
        message(FATAL_ERROR "Pinned Jolt PhysicsSystem member layout changed")
    endif()
    string(REPLACE "${gyro_marker}" "\t\t\t\tVec3 banjo_velocity_before, banjo_spin_before;\n\t\t\t\tif (mBanjoForceObserver) { banjo_velocity_before = body.GetLinearVelocity(); banjo_spin_before = body.GetAngularVelocity(); }\n${gyro_marker}" implementation "${implementation}")
    set(observation "\t\t\t\tVec3 banjo_spin_gyro;\n\t\t\t\tif (mBanjoForceObserver) banjo_spin_gyro = body.GetAngularVelocity();\n${force_marker}\n\t\t\t\tif (mBanjoForceObserver) mBanjoForceObserver(mBanjoForceContext, body, banjo_velocity_before, banjo_spin_before, banjo_spin_gyro, (mp->GetGravityFactor() * mGravity) * delta_time);")
    string(REPLACE "${force_marker}" "${observation}" implementation "${implementation}")
    set(limit_marker "\t\t\t\tmp->ClampLinearVelocity();\n\t\t\t\tmp->ClampAngularVelocity();")
    string(FIND "${implementation}" "${limit_marker}" limit_position)
    if(limit_position LESS 0)
        message(FATAL_ERROR "Pinned Jolt integration phase changed; review limit observation hook")
    endif()
    set(limit_api "\tusing BanjoLimitObserver = void (*)(void *, const Body &, Vec3Arg, Vec3Arg);\n\tvoid SetBanjoLimitObserver(BanjoLimitObserver callback, void *context) { mBanjoLimitObserver = callback; mBanjoLimitContext = context; }\n")
    string(REPLACE "${header_marker}" "${limit_api}${header_marker}" header "${header}")
    string(REPLACE "\tBanjoForceObserver mBanjoForceObserver" "\tBanjoLimitObserver mBanjoLimitObserver = nullptr;\n\tvoid *mBanjoLimitContext = nullptr;\n\tBanjoForceObserver mBanjoForceObserver" header "${header}")
    string(REPLACE "${limit_marker}" "\t\t\t\tVec3 banjo_solver_velocity, banjo_solver_spin;\n\t\t\t\tif (mBanjoLimitObserver) { banjo_solver_velocity = body.GetLinearVelocity(); banjo_solver_spin = body.GetAngularVelocity(); }\n${limit_marker}\n\t\t\t\tif (mBanjoLimitObserver) mBanjoLimitObserver(mBanjoLimitContext, body, banjo_solver_velocity, banjo_solver_spin);" implementation "${implementation}")
    file(CONFIGURE OUTPUT "${overlay}/Jolt/Physics/PhysicsSystem.h" CONTENT "${header}" @ONLY)
    file(CONFIGURE OUTPUT "${overlay}/Jolt/Physics/PhysicsSystem.cpp" CONTENT "${implementation}" @ONLY)
    get_target_property(sources ${target} SOURCES)
    get_filename_component(original "${source_dir}/Jolt/Physics/PhysicsSystem.cpp" REALPATH)
    set(source_position -1)
    set(source_index 0)
    foreach(source IN LISTS sources)
        get_filename_component(candidate "${source}" REALPATH)
        if(candidate STREQUAL original)
            if(NOT source_position LESS 0)
                message(FATAL_ERROR "Duplicate native PhysicsSystem source")
            endif()
            set(source_position ${source_index})
        endif()
        math(EXPR source_index "${source_index}+1")
    endforeach()
    if(source_position LESS 0)
        message(FATAL_ERROR "Pinned Jolt PhysicsSystem source registration changed")
    endif()
    list(REMOVE_AT sources ${source_position})
    list(APPEND sources "${overlay}/Jolt/Physics/PhysicsSystem.cpp")
    set_property(TARGET ${target} PROPERTY SOURCES "${sources}")
    target_include_directories(${target} BEFORE PUBLIC "${overlay}")
endfunction()
