import * as THREE from '/three.module.js';
import {requestScene,runSceneSteps} from '/scene-session.mjs';
import {ballObservation,cameraFrame,settingsDiffer,remainingSteps} from '/coupled-view.mjs';
const $=id=>document.getElementById(id),view=$('view');
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));view.append(renderer.domElement);
renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color('#101d26');scene.add(new THREE.HemisphereLight(0xf0f6ff,0x253c48,2));
const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(.2,.4,.3);scene.add(light);
light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-.18,right:.18,top:.18,bottom:-.18,near:.001,far:2});light.shadow.bias=-.00001;
const camera=new THREE.PerspectiveCamera(40,1,.0001,100),meshes=[];
let yaw=.5,pitch=.55,radius=.15,target=new THREE.Vector3(0,.025,0),drag=null,session=null,state=null,initial=null,busy=false,showBefore=false,showImpact=false,impactFrame=null,hash=null;
let cameraMode='target',setupPending=false,stopRequested=false,runningAction=false;
const colors={glass:0x8fd1e9,oak:0xb0875c,iron:0x9ba8b7,ice:0xcbeafa};
function cameraPose(){const r=radius*Math.max(1,1.3/camera.aspect);camera.far=Math.max(100,r*4);camera.updateProjectionMatrix();camera.position.copy(target).add(new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch)*r,Math.sin(pitch)*r,Math.cos(yaw)*Math.cos(pitch)*r));camera.lookAt(target);}
function shownState(){return showImpact?impactFrame:showBefore?initial:state;}
function frameView(mode,s=shownState()){if(!s)return;cameraMode=mode;const f=cameraFrame(s.cells,mode);target.fromArray(f.center);radius=f.radius;cameraPose();for(const m of ['target','ball','overview'])$('focus-'+m).setAttribute('aria-pressed',String(m===mode));}
function updateMarkers(){const s=shownState();if(!s)return;const o=ballObservation(s);for(const [id,position,label] of [['ball-marker',o.ball.position_m,'○ Ball'],['target-marker',cameraFrame(s.cells,'target').center,'□ Target']]){const p=new THREE.Vector3(...position).project(camera),marker=$(id);marker.hidden=cameraMode!=='overview'||p.z<-1||p.z>1||Math.abs(p.x)>1||Math.abs(p.y)>1;if(!marker.hidden){marker.style.left=((p.x+1)*view.clientWidth/2)+'px';marker.style.top=((1-p.y)*view.clientHeight/2)+'px';marker.textContent=label+' · actual position';}}}
new ResizeObserver(()=>{renderer.setSize(view.clientWidth,view.clientHeight);camera.aspect=view.clientWidth/view.clientHeight;camera.updateProjectionMatrix();cameraPose();}).observe(view);
renderer.domElement.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId);});
for(const name of ['pointerup','pointercancel'])renderer.domElement.addEventListener(name,()=>drag=null);
renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-drag.x)*.006;pitch=Math.max(-.25,Math.min(1.4,pitch+(e.clientY-drag.y)*.006));drag={x:e.clientX,y:e.clientY};cameraPose();});
renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();radius=Math.max(.04,Math.min(30,radius*Math.exp(e.deltaY*.001)));cameraPose();},{passive:false});
function build(s){for(const m of meshes){scene.remove(m);m.geometry.dispose();m.material.dispose();}meshes.length=0;
  for(const c of s.cells){const geometry=c.shape==='sphere'?new THREE.SphereGeometry(c.radius_m,24,16):c.shape==='plane'?new THREE.BoxGeometry(.3,.001,.3):new THREE.BoxGeometry(...c.size_m);
    const m=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:c.shape==='plane'?0x223640:colors[c.material],roughness:.55,metalness:c.material==='iron'?.3:0}));
    m.castShadow=c.shape!=='plane';m.receiveShadow=true;if(c.shape==='cube')m.add(new THREE.LineSegments(new THREE.EdgesGeometry(geometry),new THREE.LineBasicMaterial({color:0x294552})));scene.add(m);meshes.push(m);}
  frameView('target',s);
}
function display(){const shown=showImpact?impactFrame:showBefore?initial:state;if(!shown)return;
  for(const [i,c] of shown.cells.entries()){const m=meshes[i],q=c.quaternion_wxyz;m.position.fromArray(c.position_m);if(c.shape==='plane')m.position.y-=.0005;m.quaternion.set(q[1],q[2],q[3],q[0]);}
  const o=ballObservation(shown);if(cameraMode==='ball'){target.fromArray(o.ball.position_m);cameraPose();}
  $('drop-progress').textContent='Shown time '+shown.time_s.toFixed(4)+' s · Ball gap '+(o.contact?'Contact':o.gap_m>=.001?o.gap_m.toFixed(3)+' m':(o.gap_m*1e6).toFixed(3)+' µm')+' · '+(o.down_m_s>=0?'Falling ':'Rising ')+Math.abs(o.down_m_s).toFixed(3)+' m/s. '+(o.contact?'Ball touches a surface.': 'Gravity-only contact estimate: '+o.gravity_estimate_s.toFixed(3)+' s remaining.')+(cameraMode==='target'&&o.gap_m>.2?' Use Follow ball or Full drop to see the ball.':'');
  $('before').textContent=showBefore?'Live':'Before';$('inspect').textContent=showImpact?'Live':'Inspect ball contact';$('scene-note').lastChild.textContent=showImpact?'Ball contact view · Accepted '+impactFrame.time_s.toFixed(7)+' s · Geometric overlap '+(impactFrame.compression_m*1e6).toFixed(3)+' µm':showBefore?'Before · Accepted 0 s · Actual scale':state.declaration.experiment==='freefall'?'Normal-contact control · Actual scale · Accepted physics only':'10 mm finite cells · Actual scale · Accepted physics only';
}
function pair(name,value){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=name;dd.textContent=value;row.append(dt,dd);$('results').append(row);}
function refusalSummary(f){const counts={};for(const r of f.subdivision_refusals||[])counts[r.error]=(counts[r.error]||0)+1;
  const n=f.last_solver_failure,last=n?.iterations?.at(-1);
  return {stopped_by:f.error,accepted_time_s:f.accepted_time_s,interval_rolled_back:f.interval_rolled_back,
    contact_timestep_policy:f.contact_timestep_policy,last_contact_schedule:f.last_contact_schedule,private_elapsed_s:f.failed_interval_physical_s,private_accepted_steps_rolled_back:f.failed_interval_substeps,trial_attempts:f.trial_attempts,refusal_counts:counts,
    last_newton:n?{strategy:n.newton_strategy,attempted_fractions:n.attempted_fractions,dt_s:n.dt_s,iteration:last?.iteration,equation_residual:last?.equation_residual,
      equation_tolerance:n.equation_tolerance,line_search:last?.line_search}:null,
    note:'This is a rejected private candidate. Download the experiment log for its actual poses, forces, material history and Jacobian; the scene shows accepted physics.'};
}
function accept(reply){if(reply.state){const s=reply.state;if(hash&&hash!==s.qualification.source_sha256)throw Error('Coupled source changed; reset required');if(!initial){initial=structuredClone(s);build(s);}state=s;showBefore=showImpact=false;
    let time=s.time_s-s.substep_accounts.reduce((sum,a)=>sum+a.dt_s,0);
    for(const a of s.substep_accounts){time+=a.dt_s;const frame={time_s:time,cells:s.cells.map((c,i)=>({...c,position_m:a.poses_wxyz[i].slice(0,3),quaternion_wxyz:a.poses_wxyz[i].slice(3),velocity_m_s:a.velocities[i].slice(0,3)}))};const observation=ballObservation(frame);if(observation.contact&&(!impactFrame||-observation.gap_m>impactFrame.compression_m))impactFrame={...frame,compression_m:-observation.gap_m};}
    display();
    $('material').disabled=busy||s.declaration.experiment==='freefall';const d=s.diagnostics,p=s.performance;$('results').replaceChildren();pair('CUDA pipeline',p.pipeline==='parallel'?'Parallel':'Serial reference');pair('Newton start',p.newton_strategy==='ranked'?'Ranked starts':'Single start reference');pair('Step-size probes',p.line_search==='batch-tail'?'Full step, then GPU batch':'One at a time');pair('Linear solve',p.linear_backend==='native-cusolver'?'Resident cuSOLVER':'CuPy reference');pair('Contact timing',p.contact_resolution==='reference'?'Reference':p.contact_resolution.slice(6)+' rad');pair('Internal steps',p.microsteps);pair('Accepted time',s.time_s.toFixed(5)+' s');pair('Cells / interfaces',s.cells.length+' / '+d.interfaces);pair('Separated sites',d.separated_sites);pair('Yielded faces',d.yielded_faces);pair('Energy residual',d.global_energy_residual_j.toExponential(2)+' J');pair('Fracture / plastic work',(d.fracture_work_j+d.plastic_work_j).toExponential(2)+' J');pair('Numerical return excess',d.numerical_return_excess_j.toExponential(2)+' J');pair('Last calculation',p.last_batch_ms.toFixed(1)+' ms');pair('Physical / wall speed',p.compute_ratio===null?'—':p.compute_ratio.toFixed(5)+'×');
    const f=s.rejected_candidate;if(f){pair('Rejected trials',f.subdivision_refusals?.length??'—');pair('Scene restored',f.interval_rolled_back?'Yes':'Unconfirmed');}
    $('failure').hidden=!f;$('failure').textContent=f?JSON.stringify(refusalSummary(f),null,2):'';
  }
  if(!reply.ok)throw Error(reply.error);$('status').classList.remove('error');$('status').textContent=busy?'Calculated '+state.time_s.toFixed(4)+' simulated seconds. '+(ballObservation(state).contact?'Ball contact observed.':'Ball is still in flight.'):'Scene ready. Run to ball contact to calculate the drop.';
}
const api=requestScene;
function readSettings(){return {experiment:$('experiment').value,contact_resolution:$('contact').value,material:$('material').value,ball_material:$('ball').value,ball_mass_kg:Number($('mass').value),height_m:Number($('height').value),dt_s:1/Number($('dt').value),pipeline:$('pipeline').value,newton_strategy:$('newton').value,line_search:$('line-search').value,linear_backend:$('linear').value};}
function controls(){const pending=setupPending||settingsDiffer(state?.declaration,readSettings());for(const id of ['reset','step','run','impact','drop'])$(id).disabled=busy||(id!=='reset'&&(!session||(!pending&&(state?.rejected_candidate||!remainingSteps(state)))));$('stop').disabled=!runningAction||stopRequested;$('before').disabled=busy||!initial;$('inspect').disabled=busy||!impactFrame;for(const id of ['material','ball','mass','height','dt','pipeline','newton','line-search','linear','experiment','contact'])$(id).disabled=busy;$('material').disabled=busy||$('experiment').value==='freefall';const dt=1/Number($('dt').value);$('run').textContent='Run 10 steps · '+(10*dt).toFixed(3)+' s';$('run-hint').textContent='10 steps = '+(10*dt).toFixed(4)+' simulated seconds. A 10 m gravity-only drop takes about 1.43 s. Run to ball contact calculates accepted steps, up to the 2 s experiment limit.';}
async function step(amount){if(busy)return;if(setupPending||settingsDiffer(state?.declaration,readSettings())){await reset();if(setupPending||!state||settingsDiffer(state.declaration,readSettings()))return;}if(!state||!session)return;const remaining=remainingSteps(state),count=Math.min(remaining,amount==='contact'?remaining:amount==='0.1s'?Math.round(.1/state.dt_s):amount);if(count<1)return;busy=runningAction=true;stopRequested=false;controls();$('status').textContent='Calculating the drop on CUDA…';try{const completed=await runSceneSteps({session,count,onState:accept,shouldStop:()=>stopRequested||(amount==='contact'&&(Boolean(impactFrame)||ballObservation(state).contact)),onExpired:async()=>{session=null;busy=runningAction=false;await reset();if(session&&state)$('status').textContent='Previous scene expired. Fresh scene ready; run it again.';}});if(completed)$('status').textContent=stopRequested?'Stopped after the last accepted step at '+state.time_s.toFixed(4)+' s.':impactFrame?'Ball contact observed at '+impactFrame.time_s.toFixed(4)+' s. Use Inspect ball contact.':!remainingSteps(state)?'No ball contact observed before the 2 s experiment limit.':'Advanced to '+state.time_s.toFixed(4)+' s; ball is still in flight ('+Math.max(0,ballObservation(state).gap_m).toFixed(3)+' m gap).';}catch(e){$('status').textContent='Simulation stopped at '+(state?.time_s??0).toFixed(4)+' s: '+e.message;$('status').classList.add('error');}finally{busy=runningAction=false;controls();}}
async function reset(){if(busy||!$('mass').reportValidity()||!$('height').reportValidity())return;busy=true;controls();$('status').textContent='Creating finite CUDA cells…';try{if(session){await api({op:'close',session});session=null;}initial=state=impactFrame=null;showImpact=showBefore=false;$('log').hidden=true;await refreshCheckpoint();const reply=await api({op:'create',declaration:{solver_backend:'cupy-implicit-body',experiment:$('experiment').value,contact_resolution:$('contact').value,material:$('material').value,ball_material:$('ball').value,ball_mass_kg:Number($('mass').value),height_m:Number($('height').value),dt_s:1/Number($('dt').value),pipeline:$('pipeline').value,newton_strategy:$('newton').value,line_search:$('line-search').value,linear_backend:$('linear').value}});accept(reply);session=reply.session;setupPending=false;$('status').textContent='Scene ready. Choose a view and Run to ball contact.';$('log').href='/api/log/'+session;$('log').hidden=false;}catch(e){$('status').textContent=e.message;$('status').classList.add('error');}finally{busy=false;controls();}}
function selectExperiment(){const control=$('experiment').value==='freefall';$('contact').value=control?'phase-0.25':'reference';if(control){$('mass').value='0.1';$('height').value='0.02';}controls();}
$('experiment').addEventListener('change',selectExperiment);
if(new URLSearchParams(location.search).get('test')==='contact'){$('experiment').value='freefall';selectExperiment();}
$('reset').addEventListener('click',reset);$('step').addEventListener('click',()=>step(1));$('run').addEventListener('click',()=>step(10));$('impact').addEventListener('click',()=>step('0.1s'));$('drop').addEventListener('click',()=>step('contact'));$('stop').addEventListener('click',()=>{stopRequested=true;$('status').textContent='Stopping after the current accepted step…';controls();});$('before').addEventListener('click',()=>{showBefore=!showBefore;showImpact=false;display();});$('inspect').addEventListener('click',()=>{showImpact=!showImpact;showBefore=false;frameView('target',impactFrame);display();});
for(const mode of ['target','ball','overview'])$('focus-'+mode).addEventListener('click',()=>{frameView(mode);display();});
for(const id of ['material','ball','mass','height','dt','pipeline','newton','line-search','linear','experiment','contact'])for(const event of ['input','change'])$(id).addEventListener(event,()=>{setupPending=true;$('status').textContent='Settings changed. Run will set up the new drop first.';controls();});
window.addEventListener('pagehide',()=>{if(session)navigator.sendBeacon('/api/gpu',new Blob([JSON.stringify({op:'close',session})],{type:'application/json'}));});
window.addEventListener('pageshow',event=>{if(event.persisted)reset();});
function draw(){renderer.render(scene,camera);updateMarkers();requestAnimationFrame(draw);}cameraPose();draw();
async function refreshCheckpoint(){const response=await fetch('/api/checkpoint');if(!response.ok)throw Error('Cannot inspect the running physics build');const c=await response.json();hash=c.gpu_coupled_source_sha256;$('build').textContent='Build '+c.website_revision?.slice(0,7)+' · '+(c.gpu_coupled_source_verified&&!c.local_changes&&!c.restart_pending?'coupled source verified':'source / restart unverified');}
reset();
