import * as THREE from '/three.module.js';
import {NativePlayback} from '/playback.mjs';
const $=id=>document.getElementById(id), view=$('view');
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));view.append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#132532');
const camera=new THREE.PerspectiveCamera(48,1,.01,100), light=new THREE.DirectionalLight(0xffffff,3);light.position.set(5,12,8);scene.add(light,new THREE.AmbientLight(0xaac8df,1.5));
const grid=new THREE.GridHelper(14,28,0x78919c,0x344e5c);scene.add(grid);
const colors={glass:0x7ccce2,oak:0xb88f62,iron:0x8392a3,ice:0xb2e4f0};
const playback=new NativePlayback();let session=null,frame=0,meshes=[],current=null,busy=false,polling=false,running=false,expectedSource=null;
let following=false;let orbit={yaw:.55,pitch:.18,radius:16,target:new THREE.Vector3(0,4,0)},pointer=null;
function cameraPose(){const {yaw,pitch,radius,target}=orbit;camera.position.set(target.x+radius*Math.sin(yaw)*Math.cos(pitch),target.y+radius*Math.sin(pitch),target.z+radius*Math.cos(yaw)*Math.cos(pitch));camera.lookAt(target);}
function fit(state){const pair=state.declaration.experiment==='pair';orbit={yaw:.55,pitch:pair?.4:.13,radius:pair?1.7:Math.max(2.5,state.declaration.height_m*1.7),target:new THREE.Vector3(0,pair?0:state.declaration.height_m*.45,0)};grid.visible=!pair&&state.declaration.experiment!=='freefall';cameraPose();}
$('focus').addEventListener('click',()=>{following=!following;$('focus').textContent=following?'Whole rig':'Follow ball';if(!following&&current)fit(current);});
const ro=new ResizeObserver(()=>{camera.aspect=view.clientWidth/view.clientHeight;camera.updateProjectionMatrix();renderer.setSize(view.clientWidth,view.clientHeight,false);});ro.observe(view);
renderer.domElement.addEventListener('pointerdown',e=>{pointer={id:e.pointerId,x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId);});
renderer.domElement.addEventListener('pointermove',e=>{if(pointer?.id!==e.pointerId)return;orbit.yaw-=(e.clientX-pointer.x)*.006;orbit.pitch=Math.max(-.8,Math.min(1.3,orbit.pitch+(e.clientY-pointer.y)*.004));pointer.x=e.clientX;pointer.y=e.clientY;cameraPose();});
renderer.domElement.addEventListener('pointerup',()=>pointer=null);renderer.domElement.addEventListener('pointercancel',()=>pointer=null);
renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();orbit.radius=Math.max(.4,Math.min(40,orbit.radius*Math.exp(e.deltaY*.001)));cameraPose();},{passive:false});
function rebuild(state){for(const mesh of meshes){scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();}meshes=state.cells.map(c=>{const geometry=c.shape==='sphere'?new THREE.SphereGeometry(c.radius_m,24,16):new THREE.BoxGeometry(...c.size_m);const material=new THREE.MeshStandardMaterial({color:colors[c.material],roughness:.55,metalness:c.material==='iron'?.55:0});const mesh=new THREE.Mesh(geometry,material);scene.add(mesh);return mesh;});fit(state);}
function accept(reply){if(reply.state){const state=reply.state;if(!current){rebuild(state);playback.reset(state,performance.now());}else playback.push(state,performance.now());current=state;if(expectedSource&&state.qualification.source_sha256!==expectedSource)$('build').textContent='Running GPU worker source mismatch · reset experiment';const d=state.diagnostics,p=reply.pipeline;$('time').textContent=state.time_s.toFixed(3)+' s';$('compute').textContent=(state.performance.compute_ratio==null?'--':state.performance.compute_ratio.toFixed(2)+'×');$('speed').textContent=p?.realtime_ratio?.toFixed(2)+'×';$('contacts').textContent=d.contacts+' · '+d.max_contacts;$('total-mass').textContent=d.dynamic_mass_kg.toFixed(3)+' kg';$('energy').textContent=d.mechanical_change_j.toFixed(5)+' J';$('refusal').textContent=state.rejected_candidate?`Refused candidate: +${(Number.isFinite(state.rejected_candidate.max_gain_j)?state.rejected_candidate.max_gain_j.toPrecision(5):'nonfinite')} J maximum substep gain. Last accepted time: ${state.time_s.toFixed(3)} s. Full witness is in the record.`:'';}
frame=reply.frame_id??frame;running=!!reply.pipeline?.running;$('status').classList.toggle('error',!reply.ok);$('status').textContent=!reply.ok?reply.error:running?'Running actual GPU contacts…':reply.pipeline?.calculating?'Finishing accepted batch…':current?.time_s>=2?'Complete · inspect motion and record':'Ready · run the experiment';$('play').disabled=busy||!reply.ok||!current||current.time_s>=2||running;$('pause').disabled=!running;}
async function api(command){const response=await fetch('/api/gpu',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)});const reply=await response.json();if(!response.ok)throw Error(reply.error);return reply;}
async function poll(){if(polling)return;polling=true;const key=session;try{while(session===key&&running){const reply=await api({op:'frame',session:key,after:frame,wait_ms:250});if(session===key)accept(reply);}}catch(e){if(session===key)fail(e);}finally{polling=false;}}
function fail(e){running=false;$('status').classList.add('error');$('status').textContent=e.message;$('play').disabled=true;$('pause').disabled=true;}
$('reset').addEventListener('click',async()=>{if(busy)return;busy=true;$('reset').disabled=true;$('play').disabled=true;$('status').textContent='Creating GPU experiment; compiling kernels if needed…';try{if(session){await api({op:'close',session});session=null;}running=false;current=null;playback.reset();const reply=await api({op:'create',declaration:{experiment:$('experiment').value,material:$('material').value,ball_material:$('ball-material').value,height_m:Number($('height').value),ball_mass_kg:Number($('mass').value),restitution:Number($('restitution').value),friction:Number($('friction').value),dt_s:1/Number($('dt').value),solver_relaxation:$('experiment').value==='pair'?1:.1}});session=reply.ok?reply.session:null;frame=0;busy=false;accept(reply);if(session){$('log').href='/api/log/'+session;$('log').hidden=false;}}catch(e){fail(e);}finally{busy=false;$('reset').disabled=false;}});
$('play').addEventListener('click',async()=>{try{accept(await api({op:'play',session,running:true,target_time_s:2}));poll();}catch(e){fail(e);}});
$('pause').addEventListener('click',async()=>{try{accept(await api({op:'play',session,running:false,target_time_s:2}));}catch(e){fail(e);}});
const v=new THREE.Vector3(),q=new THREE.Quaternion();function draw(){const sample=playback.sample(performance.now());if(sample)sample.to.cells.forEach((c,i)=>{const a=sample.from.cells[i],mesh=meshes[i];mesh.position.fromArray(a.position_m);v.fromArray(c.position_m);mesh.position.lerp(v,sample.alpha);mesh.quaternion.set(a.quaternion_wxyz[1],a.quaternion_wxyz[2],a.quaternion_wxyz[3],a.quaternion_wxyz[0]);q.set(c.quaternion_wxyz[1],c.quaternion_wxyz[2],c.quaternion_wxyz[3],c.quaternion_wxyz[0]);mesh.quaternion.slerp(q,sample.alpha);});if(following&&meshes.length){orbit.target.copy(meshes.at(-1).position);orbit.radius=1.2;cameraPose();}renderer.render(scene,camera);const marker=$('ball-marker');if(meshes.length){v.copy(meshes.at(-1).position).project(camera);marker.hidden=Math.abs(v.x)>1||Math.abs(v.y)>1||v.z>1;marker.style.left=((v.x+1)*view.clientWidth/2-56)+'px';marker.style.top=((1-v.y)*view.clientHeight/2-25)+'px';}else marker.hidden=true;requestAnimationFrame(draw);}cameraPose();draw();
for(const control of document.querySelectorAll('select,input'))control.addEventListener('change',()=>{$('target-row').hidden=!['pair','yard'].includes($('experiment').value);$('height-row').hidden=$('experiment').value==='pair';if(session&&!running){$('play').disabled=true;$('status').textContent='Changes pending · Set up to apply';}});
fetch('/api/checkpoint').then(r=>r.json()).then(build=>{expectedSource=build.gpu_source_sha256;$('build').textContent=`Build ${build.website_revision?.slice(0,7)} · ${build.gpu_available&&build.gpu_source_verified&&!build.local_changes&&!build.restart_pending?'GPU source verified':'GPU source / runtime unverified'}`;}).catch(e=>$('build').textContent=e.message);
