import * as THREE from '/three.module.js';
import {acceptedFrameIndex,verifyMechanismReceipt,mechanismMotionFrame} from '/mechanisms-view.mjs';
const $=id=>document.getElementById(id),view=$('view'),scene=new THREE.Scene();scene.background=new THREE.Color(0x0d202c);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));view.prepend(renderer.domElement);
const camera=new THREE.PerspectiveCamera(45,1,.01,100),target=new THREE.Vector3(0,1,0);let distance=3.3,azimuth=.3,elevation=.16,drag=null,data=null,index=0,playing=false,start=0,offset=0;
scene.add(new THREE.HemisphereLight(0xe4f4ff,0x243c48,2));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(3,5,5);scene.add(light);
const grid=new THREE.GridHelper(12,24,0x365e76,0x213f52);grid.position.y=-.05;scene.add(grid);
const pin=new THREE.Mesh(new THREE.SphereGeometry(.065,20,12),new THREE.MeshStandardMaterial({color:0xffc66a}));pin.position.set(0,1.5,0);scene.add(pin);
let bar=null,followBody=false;const reaction=new THREE.ArrowHelper(new THREE.Vector3(0,1,0),pin.position,.6,0xffc66a,.12,.07);scene.add(reaction);
const colors={glass:0x94d2e8,oak:0xa97b55,iron:0xa6b7cb,ice:0xc4eafa};
function pose(){camera.position.copy(target).add(new THREE.Vector3(Math.sin(azimuth)*Math.cos(elevation)*distance,Math.sin(elevation)*distance,Math.cos(azimuth)*Math.cos(elevation)*distance));camera.lookAt(target);}
new ResizeObserver(()=>{camera.aspect=view.clientWidth/view.clientHeight;camera.updateProjectionMatrix();renderer.setSize(view.clientWidth,view.clientHeight);if(data&&!followBody){const f=mechanismMotionFrame(data,camera.aspect);target.fromArray(f.center);distance=f.distance;}pose();}).observe(view);
renderer.domElement.addEventListener('pointerdown',e=>{drag=[e.clientX,e.clientY];renderer.domElement.setPointerCapture(e.pointerId);});
renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;azimuth-=(e.clientX-drag[0])*.006;elevation=Math.max(-1.4,Math.min(1.4,elevation+(e.clientY-drag[1])*.006));drag=[e.clientX,e.clientY];pose();});
for(const event of ['pointerup','pointercancel'])renderer.domElement.addEventListener(event,()=>drag=null);
renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(.4,Math.min(30,distance*Math.exp(e.deltaY*.001)));pose();},{passive:false});
function pair(name,value){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=name;dd.textContent=value;row.append(dt,dd);$('metrics').append(row);}
function draw(){if(!data||!bar)return;const f=data.frames[index];bar.position.fromArray(f.com_m);bar.rotation.z=f.angle_rad;if(followBody)target.fromArray(f.com_m);pose();pin.visible=f.mode!=='rigid-free';reaction.visible=pin.visible&&index>0;
  const receipt=data.receipts[Math.max(0,index-1)];if(receipt){const v=new THREE.Vector3(...receipt.support_impulse_ns).divideScalar(data.audit.dt_s),magnitude=v.length();reaction.visible=pin.visible&&magnitude>1e-10;if(magnitude>1e-10)reaction.setDirection(v.normalize());}
  $('time-label').textContent=f.time_s.toFixed(3)+' s · '+f.mode+' · '+(f.angle_rad*180/Math.PI).toFixed(1)+'° · '+f.omega_rad_s.toFixed(2)+' rad/s';$('scrub').value=String(index);
}
function clear(){if(bar){scene.remove(bar);bar.geometry.dispose();bar.material.dispose();for(const c of bar.children){c.geometry.dispose();c.material.dispose();}}}
const bindings={'length':'length_m','width':'width_m','thickness':'thickness_m','density':'density_kg_m3','angle':'angle_deg','omega':'omega_rad_s','gravity':'gravity_m_s2','force-x':'force_x_n','force-y':'force_y_n','torque':'torque_nm','load-time':'load_time_s','release-time':'release_time_s','duration':'duration_s','dt':'dt_s'};
async function calculate(event){event?.preventDefault();if(!$('settings').reportValidity())return;playing=false;$('calculate').disabled=true;$('status').textContent='Solving native dynamics and auditing work/reactions…';
  try{const payload={material:$('material').value};for(const [id,key]of Object.entries(bindings))payload[key]=Number($(id).value);
    const response=await fetch('/api/mechanisms/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok||result.ok===false)throw Error(result.error??'Native experiment refused');
    data=verifyMechanismReceipt(result.result??result);clear();const g=data.geometry;bar=new THREE.Mesh(new THREE.BoxGeometry(g.width_m,g.length_m,g.thickness_m),new THREE.MeshStandardMaterial({color:colors[data.material],roughness:.5,metalness:0}));bar.add(new THREE.LineSegments(new THREE.EdgesGeometry(bar.geometry),new THREE.LineBasicMaterial({color:0x172c36})));scene.add(bar);
    index=0;followBody=false;const framing=mechanismMotionFrame(data,camera.aspect);target.fromArray(framing.center);distance=framing.distance;$('fit').textContent='Follow body';$('scrub').max=String(data.frames.length-1);$('scrub').disabled=false;for(const id of ['before','play','after'])$(id).disabled=false;
    $('build').textContent='Native '+data.native_sha256.slice(0,10)+' · source '+data.source_sha256.slice(0,10);$('metrics').replaceChildren();const a=data.audit;
    pair('Mass',data.mass_kg.toFixed(3)+' kg');pair('Pin inertia',data.inertia_pin_kg_m2.toFixed(4)+' kg m²');pair('Accepted time',a.accepted_time_s.toFixed(3)+' s');pair('Calculation', (a.calculation_wall_s*1000).toFixed(2)+' ms');pair('Energy residual',a.energy_residual_j.toExponential(2)+' J');pair('Angular residual',a.max_angular_residual_nms.toExponential(2)+' N m s');pair('External work',a.external_work_j.toFixed(4)+' J');pair('Sleep time',(a.sleep_steps*a.dt_s).toFixed(3)+' s');pair('Omitted sleeping motion','0 m · exact equilibrium only');
    $('limits').replaceChildren(...data.limits.map(text=>{const li=document.createElement('li');li.textContent=text;return li;}));$('status').textContent='Accepted native trajectory. Changing material changes density/mass; this ideal rigid reference has no damage law. Playback follows physical time.';draw();if(matchMedia("(max-width:800px)").matches)view.scrollIntoView({block:"start"});play();
  }catch(e){$('status').textContent='Experiment refused: '+e.message;}finally{$('calculate').disabled=false;}
}
function play(){if(!data)return;if(playing){playing=false;$('play').textContent='Play';return;}if(index===data.frames.length-1)index=0;offset=data.frames[index].time_s;start=performance.now();playing=true;$('play').textContent='Pause';}
function stopAt(i){playing=false;$('play').textContent='Play';index=i;draw();}
$('settings').addEventListener('submit',calculate);$('play').addEventListener('click',play);$('before').addEventListener('click',()=>stopAt(0));$('after').addEventListener('click',()=>stopAt(data.frames.length-1));$('scrub').addEventListener('input',()=>stopAt(Number($('scrub').value)));$('fit').addEventListener('click',()=>{if(!data)return;followBody=!followBody;$('fit').textContent=followBody?'Whole motion':'Follow body';if(followBody)distance=data.geometry.length_m*3;else{const f=mechanismMotionFrame(data,camera.aspect);target.fromArray(f.center);distance=f.distance;}draw();pose();});
$('material').addEventListener('change',()=>{$('density').value=String({glass:2500,oak:700,iron:7870,ice:917}[$('material').value]);});
function scenario(angle,fx,load,release,duration){$('angle').value=String(angle);$('omega').value='0';$('force-x').value=String(fx);$('force-y').value='0';$('torque').value='0';$('load-time').value=String(load);$('release-time').value=String(release);$('duration').value=String(duration);$('gravity').value='9.81';calculate();}
$('pendulum').addEventListener('click',()=>scenario(35,0,0,10,3));$('wake').addEventListener('click',()=>scenario(0,10,.5,10,3));$('release').addEventListener('click',()=>scenario(0,0,0,.5,1.5));
function tick(now){if(playing&&data){const t=offset+(now-start)/1000;index=acceptedFrameIndex(data.frames,t);draw();if(index===data.frames.length-1){playing=false;$('play').textContent='Play';}}renderer.render(scene,camera);requestAnimationFrame(tick);}pose();requestAnimationFrame(tick);
fetch('/api/checkpoint').then(r=>r.json()).then(c=>$('build').textContent='Website '+c.website_revision?.slice(0,8)+' · mechanism not calculated').catch(()=>$('build').textContent='Build unavailable');
