import * as THREE from '/three.module.js';
const $=id=>document.getElementById(id),view=$('view'),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));view.append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#182b35');const camera=new THREE.PerspectiveCamera(45,1,.001,5);scene.add(new THREE.AmbientLight(0xffffff,1.8));const lamp=new THREE.DirectionalLight(0xffffff,2);lamp.position.set(.1,.2,.1);scene.add(lamp);
const grid=new THREE.GridHelper(.12,12,0x507281,0x294b59);grid.position.y=-.006;scene.add(grid);
let meshes=[],state=null,session=null,busy=false,running=false,selected=0,orbit={yaw:.5,pitch:.8,radius:.13},pointer=null,moved=false;
for(let i=0;i<24;i++){const option=document.createElement('option');option.value=i;option.textContent=`Cell ${i+1}`;$('source').append(option);}
function pose(){const radius=orbit.radius*Math.max(1,1/camera.aspect);camera.position.set(Math.sin(orbit.yaw)*Math.cos(orbit.pitch)*radius,Math.sin(orbit.pitch)*radius,Math.cos(orbit.yaw)*Math.cos(orbit.pitch)*radius);camera.lookAt(0,0,0);}
new ResizeObserver(()=>{renderer.setSize(view.clientWidth,view.clientHeight);camera.aspect=view.clientWidth/view.clientHeight;camera.updateProjectionMatrix();pose();}).observe(view);pose();
const ray=new THREE.Raycaster();renderer.domElement.addEventListener('pointerdown',e=>{pointer={x:e.clientX,y:e.clientY};moved=false;renderer.domElement.setPointerCapture(e.pointerId);});renderer.domElement.addEventListener('pointermove',e=>{if(!pointer)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(Math.abs(dx)+Math.abs(dy)>2)moved=true;orbit.yaw-=dx*.008;orbit.pitch=Math.max(.15,Math.min(1.45,orbit.pitch+dy*.008));pointer={x:e.clientX,y:e.clientY};pose();});renderer.domElement.addEventListener('pointerup',e=>{pointer=null;if(moved)return;const rect=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2(2*(e.clientX-rect.left)/rect.width-1,1-2*(e.clientY-rect.top)/rect.height),camera);const hit=ray.intersectObjects(meshes)[0];if(hit){selected=hit.object.userData.index;$('source').value=selected;display();}});renderer.domElement.addEventListener('pointercancel',()=>pointer=null);renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();orbit.radius=Math.min(.4,Math.max(.05,orbit.radius*Math.exp(e.deltaY*.001)));pose();},{passive:false});
function rows(id,values){$(id).replaceChildren(...values.map(([key,value])=>{const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;div.append(dt,dd);return div;}));}
function fieldValue(c){const f=$('field').value;if(f==='temperature')return c.temperature_k;if(f==='phase')return c.liquid_fraction;if(f==='fuel')return c.fuel_kg/(c.thermal_mass_kg*.9)||0;return c.products_kg/c.species_mass_kg;}
function display(){if(!state)return;const field=$('field').value,values=state.cells.map(fieldValue),low=field==='temperature'?Math.min(...values):0,high=field==='temperature'?Math.max(low+1,...values):field==='fuel'?1:Math.max(.001,...values);$('legend').textContent=field==='temperature'?`Temperature · ${low.toFixed(2)} K blue → ${high.toFixed(2)} K red · measured range`:field==='phase'?`Liquid fraction · 0 blue → ${(high*100).toFixed(2)}% yellow · measured range`:field==='fuel'?'Remaining fuel · 0 dark → 100% green':`Retained products · 0 dark → ${(high*100).toFixed(2)}% amber · measured range`;
 state.cells.forEach((c,i)=>{const val=Math.max(0,Math.min(1,(values[i]-low)/(high-low))),color=new THREE.Color();if(field==='temperature')color.setHSL((1-val)*.65,.85,.43);else if(field==='phase')color.setHSL(.62-val*.5,.85,.3+val*.3);else color.setHSL(field==='fuel'?.3:.09,.65,.12+val*.45);meshes[i].material.color.copy(color);meshes[i].children[0].material.color.set(i===selected?0xffffff:0x172b36);});
 const c=state.cells[selected],a=state.audit;$('clock').textContent=`${state.time_s.toFixed(2)} physical seconds`;rows('cell-info',[['Cell',selected+1],['Temperature',`${c.temperature_k.toFixed(2)} K`],['Liquid fraction',`${(100*c.liquid_fraction).toFixed(1)}%`],['Thermal energy',`${c.enthalpy_j.toFixed(3)} J`],['Fuel',`${(c.fuel_kg*1000).toFixed(4)} g`],['Oxygen',`${(c.oxygen_kg*1000).toFixed(4)} g`],['Products',`${(c.products_kg*1000).toFixed(4)} g`]]);rows('audit',[['Heater input',`${a.external_heat_j.toFixed(3)} J`],['Chemical → heat',`${a.converted_chemical_j.toFixed(3)} J`],['Energy residual',`${a.energy_residual_j.toExponential(2)} J`],['Species mass residual',`${a.mass_residual_kg.toExponential(2)} kg`],['Compute',`${a.calculation_wall_s.toFixed(4)} s`],['Physical / compute',a.calculation_wall_s?`${(state.time_s/a.calculation_wall_s).toFixed(1)}×`:'—']]);}
function accept(reply){if(!reply.ok)throw Error(reply.error);state=reply.state;if(!meshes.length){state.cells.forEach((c,i)=>{const geometry=new THREE.BoxGeometry(c.size_m,c.size_m,c.size_m),mesh=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({roughness:.65}));mesh.position.fromArray(c.position_m);mesh.userData.index=i;mesh.add(new THREE.LineSegments(new THREE.EdgesGeometry(geometry),new THREE.LineBasicMaterial({color:0x172b36})));meshes.push(mesh);scene.add(mesh);});}display();$('build').textContent=`Native ${state.implementation.binary_sha256.slice(0,12)} · source ${state.implementation.source_sha256.slice(0,12)} · experimental fields`;}
async function api(command){const response=await fetch('/api/thermal-fields',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)}),reply=await response.json();if(!response.ok||!reply.ok)throw Error(reply.error||'Field request refused');return reply;}
function controls(){for(const id of ['reset','step','run','save','open','ice-test','fuel-test'])$(id).disabled=busy||running; $('stop').disabled=!running;}
function error(e){running=false;$('status').textContent=e.message;$('status').classList.add('error');controls();}
async function create(){if(busy||running)return;busy=true;controls();try{if(session)await api({op:'close',session});session=null;const reply=await api({op:'create',declaration:{material:$('material').value,initial_temperature_k:Number($('temperature').value),heater_w:Number($('power').value),heater_cell:Number($('source').value),oxygen_fraction:Number($('oxygen').value),reaction:$('reaction').checked,dt_s:.05}});session=reply.session;accept(reply);$('status').classList.remove('error');$('status').textContent='Ready · heat evolves through native fields. Selection marks the heater for your next setup.';$('log').href='/api/log/'+session;$('log').hidden=false;}catch(e){error(e);}finally{busy=false;controls();}}
async function advance(duration){if(busy||running||!session)return;running=true;controls();const target=state.time_s+duration;try{while(running&&state.time_s<target-1e-8){const steps=Math.min(200,Math.round((target-state.time_s)/state.declaration.dt_s));accept(await api({op:'advance',session,steps}));$('status').textContent='Calculating native heat, phase and species budgets…';await new Promise(resolve=>requestAnimationFrame(resolve));}$('status').textContent='Accepted state · heat and species shown above; geometry remains fixed.';}catch(e){error(e);}finally{running=false;controls();}}
$('reset').onclick=create;$('run').onclick=()=>advance(20);$('step').onclick=()=>advance(1);$('stop').onclick=()=>{running=false;};$('field').onchange=display;
$('save').onclick=async()=>{try{const reply=await api({op:'export',session}),blob=new Blob([JSON.stringify(reply.checkpoint)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='banjo-thermal-fields.json';a.click();URL.revokeObjectURL(url);}catch(e){error(e);}};
$('open').onclick=()=>$('file').click();$('file').onchange=async()=>{try{const file=$('file').files[0];if(!file)return;if(file.size>100000)throw Error('Checkpoint too large');const checkpoint=JSON.parse(await file.text()),reply=await api({op:'restore',checkpoint});if(session)await api({op:'close',session});session=reply.session;accept(reply);$('status').textContent='Exact native field history reopened.';$('log').href='/api/log/'+session;$('log').hidden=false;}catch(e){error(e);}finally{$('file').value='';}};
$('material').onchange=()=>{if($('material').value!=='oak')$('reaction').checked=false;$('reaction').disabled=$('material').value!=='oak';};$('material').onchange();
$('ice-test').onclick=()=>{if(busy||running)return;$('material').value='ice';$('material').onchange();$('temperature').value=273.15;$('power').value=2;$('field').value='phase';create();};
$('fuel-test').onclick=()=>{if(busy||running)return;$('material').value='oak';$('material').onchange();$('temperature').value=550;$('power').value=20;$('reaction').checked=true;$('field').value='products';create();};
function render(){renderer.render(scene,camera);requestAnimationFrame(render);}render();fetch('/api/checkpoint').then(r=>r.json()).then(b=>{$('build').textContent=`Website ${b.website_revision?.slice(0,7)} · setting up native scalar fields`;create();}).catch(error);
